### ISSUE TITLE
minion: tell X about copying

### ISSUE THREAD

**Issue by phoe** [stassats/lisp-bots#14]
The issue of copying instances (or, equivalently, "is there a way to copy a standard-object") happens often enough on `#lisp` and not only there that I propose to add a command to minion's database.

query: `minion: tell X about copying`
expected response: http://www.nhplace.com/kent/PS/EQUAL.html

**Comment by stassats** [comment]
https://github.com/stassats/lisp-bots/blob/master/minion/minion.lisp#L350
